<?php

namespace Database\Seeders;

use App\Models\Patient;
use Illuminate\Database\Seeder;

class PatientSeeder extends Seeder
{
    public function run(): void
    {
        $patients = [
            [
                'first_name' => 'John',
                'last_name' => 'Smith',
                'date_of_birth' => '1985-03-15',
                'gender' => 'male',
                'email' => 'john.smith@email.com',
                'phone' => '+1-555-1001',
                'address' => '123 Main Street',
                'city' => 'New York',
                'postal_code' => '10001',
                'emergency_contact_name' => 'Jane Smith',
                'emergency_contact_phone' => '+1-555-1002',
                'medical_history' => 'Hypertension, controlled with medication',
                'allergies' => 'Penicillin',
                'current_medications' => 'Lisinopril 10mg daily',
                'insurance_provider' => 'Blue Cross Blue Shield',
                'insurance_policy_number' => 'BCBS-12345678',
            ],
            [
                'first_name' => 'Maria',
                'last_name' => 'Garcia',
                'date_of_birth' => '1992-07-22',
                'gender' => 'female',
                'email' => 'maria.garcia@email.com',
                'phone' => '+1-555-1003',
                'address' => '456 Oak Avenue',
                'city' => 'Los Angeles',
                'postal_code' => '90210',
                'emergency_contact_name' => 'Carlos Garcia',
                'emergency_contact_phone' => '+1-555-1004',
                'medical_history' => 'No significant medical history',
                'allergies' => 'None known',
                'current_medications' => 'Birth control pills',
                'insurance_provider' => 'Aetna',
                'insurance_policy_number' => 'AETNA-87654321',
            ],
            [
                'first_name' => 'Robert',
                'last_name' => 'Wilson',
                'date_of_birth' => '1978-11-08',
                'gender' => 'male',
                'email' => 'robert.wilson@email.com',
                'phone' => '+1-555-1005',
                'address' => '789 Pine Street',
                'city' => 'Chicago',
                'postal_code' => '60601',
                'emergency_contact_name' => 'Lisa Wilson',
                'emergency_contact_phone' => '+1-555-1006',
                'medical_history' => 'Type 2 Diabetes, well controlled',
                'allergies' => 'Latex',
                'current_medications' => 'Metformin 500mg twice daily',
                'insurance_provider' => 'Cigna',
                'insurance_policy_number' => 'CIGNA-11223344',
            ],
            [
                'first_name' => 'Emily',
                'last_name' => 'Davis',
                'date_of_birth' => '1995-05-30',
                'gender' => 'female',
                'email' => 'emily.davis@email.com',
                'phone' => '+1-555-1007',
                'address' => '321 Elm Street',
                'city' => 'Miami',
                'postal_code' => '33101',
                'emergency_contact_name' => 'Michael Davis',
                'emergency_contact_phone' => '+1-555-1008',
                'medical_history' => 'Asthma, mild intermittent',
                'allergies' => 'Shellfish, pollen',
                'current_medications' => 'Albuterol inhaler as needed',
                'insurance_provider' => 'United Healthcare',
                'insurance_policy_number' => 'UHC-55667788',
            ],
            [
                'first_name' => 'James',
                'last_name' => 'Brown',
                'date_of_birth' => '1970-12-12',
                'gender' => 'male',
                'email' => 'james.brown@email.com',
                'phone' => '+1-555-1009',
                'address' => '654 Maple Drive',
                'city' => 'Houston',
                'postal_code' => '77001',
                'emergency_contact_name' => 'Patricia Brown',
                'emergency_contact_phone' => '+1-555-1010',
                'medical_history' => 'High cholesterol, heart murmur',
                'allergies' => 'Iodine',
                'current_medications' => 'Atorvastatin 20mg daily',
                'insurance_provider' => 'Humana',
                'insurance_policy_number' => 'HUM-99887766',
            ],
            [
                'first_name' => 'Sarah',
                'last_name' => 'Miller',
                'date_of_birth' => '1988-09-18',
                'gender' => 'female',
                'email' => 'sarah.miller@email.com',
                'phone' => '+1-555-1011',
                'address' => '987 Cedar Lane',
                'city' => 'Phoenix',
                'postal_code' => '85001',
                'emergency_contact_name' => 'David Miller',
                'emergency_contact_phone' => '+1-555-1012',
                'medical_history' => 'Migraines, occasional',
                'allergies' => 'Sulfa drugs',
                'current_medications' => 'Sumatriptan as needed for migraines',
                'insurance_provider' => 'Kaiser Permanente',
                'insurance_policy_number' => 'KP-44556677',
            ],
            [
                'first_name' => 'Michael',
                'last_name' => 'Johnson',
                'date_of_birth' => '2010-04-25',
                'gender' => 'male',
                'email' => 'contact@johnson-family.com',
                'phone' => '+1-555-1013',
                'address' => '147 Birch Street',
                'city' => 'Seattle',
                'postal_code' => '98101',
                'emergency_contact_name' => 'Jennifer Johnson',
                'emergency_contact_phone' => '+1-555-1014',
                'medical_history' => 'ADHD, well managed',
                'allergies' => 'None known',
                'current_medications' => 'Methylphenidate 10mg daily',
                'insurance_provider' => 'Blue Cross Blue Shield',
                'insurance_policy_number' => 'BCBS-33445566',
            ],
            [
                'first_name' => 'Ashley',
                'last_name' => 'Taylor',
                'date_of_birth' => '1983-08-07',
                'gender' => 'female',
                'email' => 'ashley.taylor@email.com',
                'phone' => '+1-555-1015',
                'address' => '258 Spruce Avenue',
                'city' => 'Denver',
                'postal_code' => '80201',
                'emergency_contact_name' => 'Ryan Taylor',
                'emergency_contact_phone' => '+1-555-1016',
                'medical_history' => 'Pregnancy - expecting in 3 months',
                'allergies' => 'Codeine',
                'current_medications' => 'Prenatal vitamins',
                'insurance_provider' => 'Anthem',
                'insurance_policy_number' => 'ANT-22334455',
            ],
        ];

        foreach ($patients as $patient) {
            Patient::create($patient);
        }
    }
}