<?php

namespace Database\Seeders;

use App\Models\Patient;
use Illuminate\Database\Seeder;

class PatientSeeder extends Seeder
{
    public function run(): void
    {
        $patients = [
            [
                'first_name' => 'John',
                'last_name' => 'Smith',
                'date_of_birth' => '1985-03-15',
                'gender' => 'male',
                'email' => 'john.smith@email.com',
                'phone' => '+1-555-1001',
                'address' => '123 Main Street',
                'city' => 'New York',
                'postal_code' => '10001',
                'emergency_contact_name' => 'Jane Smith',
                'emergency_contact_phone' => '+1-555-1002',
                'medical_history' => 'Hypertension, controlled with medication',
                'allergies' => 'Penicillin',
                'current_medications' => 'Lisinopril 10mg daily',
                'insurance_provider' => 'Blue Cross Blue Shield',
                'insurance_policy_number' => 'BCBS-12345678',
            ],
            [
                'first_name' => 'Maria',
                'last_name' => 'Garcia',
                'date_of_birth' => '1992-07-22',
                'gender' => 'female',
                'email' => 'maria.garcia@email.com',
                'phone' => '+1-555-1003',
                'address' => '456 Oak Avenue',
                'city' => 'Los Angeles',
                'postal_code' => '90210',
                'emergency_contact_name' => 'Carlos Garcia',
                'emergency_contact_phone' => '+1-555-1004',
                'medical_history' => 'No significant medical history',
                'allergies' => 'None known',
                'current_medications' => 'Birth control pills',
                'insurance_provider' => 'Aetna',
                'insurance_policy_number' => 'AETNA-87654321',
            ],
            [
                'first_name' => 'Robert',
                'last_name' => 'Wilson',
                'date_of_birth' => '1978-11-08',
                'gender' => 'male',
                'email' => 'robert.wilson@email.com',
                'phone' => '+1-555-1005',
                'address' => '789 Pine Street',
                'city' => 'Chicago',
                'postal_code' => '60601',
                'emergency_contact_name' => 'Lisa Wilson',
                'emergency_contact_phone' => '+1-555-1006',
                'medical_history' => 'Type 2 Diabetes, well controlled',
                'allergies' => 'Latex',
                'current_medications' => 'Metformin 500mg twice daily',
                'insurance_provider' => 'Cigna',
                'insurance_policy_number' => 'CIGNA-11223344',
            ],
            [
                'first_name' => 'Emily',
                'last_name' => 'Davis',
                'date_of_birth' => '1995-05-30',
                'gender' => 'female',
                'email' => 'emily.davis@email.com',
                'phone' => '+1-555-1007',
                'address' => '321 Elm Street',
                'city' => 'Miami',
                'postal_code' => '33101',
                'emergency_contact_name' => 'Michael Davis',
                'emergency_contact_phone' => '+1-555-1008',
                'medical_history' => 'Asthma, mild intermittent',
                'allergies' => 'Shellfish, pollen',
                'current_medications' => 'Albuterol inhaler as needed',
                'insurance_provider' => 'United Healthcare',
                'insurance_policy_number' => 'UHC-55667788',
            ],
            [
                'first_name' => 'James',
                'last_name' => 'Brown',
                'date_of_birth' => '1970-12-12',
                'gender' => 'male',
                'email' => 'james.brown@email.com',
                'phone' => '+1-555-1009',
                'address' => '654 Maple Drive',
                'city' => 'Houston',
                'postal_code' => '77001',
                'emergency_contact_name' => 'Patricia Brown',
                'emergency_contact_phone' => '+1-555-1010',
                'medical_history' => 'High cholesterol, heart murmur',
                'allergies' => 'Iodine',
                'current_medications' => 'Atorvastatin 20mg daily',
                'insurance_provider' => 'Humana',
                'insurance_policy_number' => 'HUM-99887766',
            ],
            [
                'first_name' => 'Sarah',
                'last_name' => 'Miller',
                'date_of_birth' => '1988-09-18',
                'gender' => 'female',
                'email' => 'sarah.miller@email.com',
                'phone' => '+1-555-1011',
                'address' => '987 Cedar Lane',
                'city' => 'Phoenix',
                'postal_code' => '85001',
                'emergency_contact_name' => 'David Miller',
                'emergency_contact_phone' => '+1-555-1012',
                'medical_history' => 'Migraines, occasional',
                'allergies' => 'Sulfa drugs',
                'current_medications' => 'Sumatriptan as needed for migraines',
                'insurance_provider' => 'Kaiser Permanente',
                'insurance_policy_number' => 'KP-44556677',
            ],
            [
                'first_name' => 'Michael',
                'last_name' => 'Johnson',
                'date_of_birth' => '2010-04-25',
                'gender' => 'male',
                'email' => 'contact@johnson-family.com',
                'phone' => '+1-555-1013',
                'address' => '147 Birch Street',
                'city' => 'Seattle',
                'postal_code' => '98101',
                'emergency_contact_name' => 'Jennifer Johnson',
                'emergency_contact_phone' => '+1-555-1014',
                'medical_history' => 'ADHD, well managed',
                'allergies' => 'None known',
                'current_medications' => 'Methylphenidate 10mg daily',
                'insurance_provider' => 'Blue Cross Blue Shield',
                'insurance_policy_number' => 'BCBS-33445566',
            ],
            [
                'first_name' => 'Ashley',
                'last_name' => 'Taylor',
                'date_of_birth' => '1983-08-07',
                'gender' => 'female',
                'email' => 'ashley.taylor@email.com',
                'phone' => '+1-555-1015',
                'address' => '258 Spruce Avenue',
                'city' => 'Denver',
                'postal_code' => '80201',
                'emergency_contact_name' => 'Ryan Taylor',
                'emergency_contact_phone' => '+1-555-1016',
                'medical_history' => 'Pregnancy - expecting in 3 months',
                'allergies' => 'Codeine',
                'current_medications' => 'Prenatal vitamins',
                'insurance_provider' => 'Anthem',
                'insurance_policy_number' => 'ANT-22334455',
            ],
            [
                'first_name' => 'Christopher',
                'last_name' => 'Anderson',
                'date_of_birth' => '1990-01-14',
                'gender' => 'male',
                'email' => 'chris.anderson@email.com',
                'phone' => '+1-555-1017',
                'address' => '369 Willow Court',
                'city' => 'Boston',
                'postal_code' => '02101',
                'emergency_contact_name' => 'Michelle Anderson',
                'emergency_contact_phone' => '+1-555-1018',
                'medical_history' => 'No significant medical history',
                'allergies' => 'None known',
                'current_medications' => 'None',
                'insurance_provider' => 'Blue Cross Blue Shield',
                'insurance_policy_number' => 'BCBS-77889900',
            ],
            [
                'first_name' => 'Jessica',
                'last_name' => 'Martinez',
                'date_of_birth' => '1986-06-21',
                'gender' => 'female',
                'email' => 'jessica.martinez@email.com',
                'phone' => '+1-555-1019',
                'address' => '741 River Road',
                'city' => 'San Diego',
                'postal_code' => '92101',
                'emergency_contact_name' => 'Carlos Martinez',
                'emergency_contact_phone' => '+1-555-1020',
                'medical_history' => 'Thyroid disorder, hypothyroidism',
                'allergies' => 'Aspirin',
                'current_medications' => 'Levothyroxine 75mcg daily',
                'insurance_provider' => 'Kaiser Permanente',
                'insurance_policy_number' => 'KP-11223344',
            ],
            [
                'first_name' => 'Daniel',
                'last_name' => 'White',
                'date_of_birth' => '2005-03-10',
                'gender' => 'male',
                'email' => 'white.family@email.com',
                'phone' => '+1-555-1021',
                'address' => '852 Valley Drive',
                'city' => 'Portland',
                'postal_code' => '97201',
                'emergency_contact_name' => 'Susan White',
                'emergency_contact_phone' => '+1-555-1022',
                'medical_history' => 'Braces completed last year',
                'allergies' => 'None known',
                'current_medications' => 'None',
                'insurance_provider' => 'Aetna',
                'insurance_policy_number' => 'AETNA-55667788',
            ],
            [
                'first_name' => 'Nicole',
                'last_name' => 'Harris',
                'date_of_birth' => '1975-11-29',
                'gender' => 'female',
                'email' => 'nicole.harris@email.com',
                'phone' => '+1-555-1023',
                'address' => '963 Mountain View',
                'city' => 'Austin',
                'postal_code' => '78701',
                'emergency_contact_name' => 'Kevin Harris',
                'emergency_contact_phone' => '+1-555-1024',
                'medical_history' => 'Osteoporosis, anxiety disorder',
                'allergies' => 'Latex, nickel',
                'current_medications' => 'Alendronate 70mg weekly, Sertraline 50mg daily',
                'insurance_provider' => 'Cigna',
                'insurance_policy_number' => 'CIGNA-99887766',
            ],
            [
                'first_name' => 'Brian',
                'last_name' => 'Clark',
                'date_of_birth' => '1998-09-05',
                'gender' => 'male',
                'email' => 'brian.clark@email.com',
                'phone' => '+1-555-1025',
                'address' => '159 Lake Shore Boulevard',
                'city' => 'San Francisco',
                'postal_code' => '94101',
                'emergency_contact_name' => 'Angela Clark',
                'emergency_contact_phone' => '+1-555-1026',
                'medical_history' => 'Previous wisdom teeth removal',
                'allergies' => 'Seasonal allergies',
                'current_medications' => 'Loratadine as needed',
                'insurance_provider' => 'Blue Shield',
                'insurance_policy_number' => 'BSC-44332211',
            ],
            [
                'first_name' => 'Amanda',
                'last_name' => 'Lewis',
                'date_of_birth' => '1982-02-18',
                'gender' => 'female',
                'email' => 'amanda.lewis@email.com',
                'phone' => '+1-555-1027',
                'address' => '753 Park Avenue',
                'city' => 'Atlanta',
                'postal_code' => '30301',
                'emergency_contact_name' => 'Thomas Lewis',
                'emergency_contact_phone' => '+1-555-1028',
                'medical_history' => 'Depression, well controlled',
                'allergies' => 'Penicillin, shellfish',
                'current_medications' => 'Fluoxetine 20mg daily',
                'insurance_provider' => 'United Healthcare',
                'insurance_policy_number' => 'UHC-22446688',
            ],
            [
                'first_name' => 'Steven',
                'last_name' => 'Robinson',
                'date_of_birth' => '1968-07-12',
                'gender' => 'male',
                'email' => 'steven.robinson@email.com',
                'phone' => '+1-555-1029',
                'address' => '486 Summit Street',
                'city' => 'Philadelphia',
                'postal_code' => '19101',
                'emergency_contact_name' => 'Karen Robinson',
                'emergency_contact_phone' => '+1-555-1030',
                'medical_history' => 'Heart disease, previous heart attack, high blood pressure',
                'allergies' => 'Aspirin, epinephrine',
                'current_medications' => 'Metoprolol 50mg twice daily, Aspirin 81mg daily, Lisinopril 20mg daily',
                'insurance_provider' => 'Medicare',
                'insurance_policy_number' => 'MED-123456789',
            ],
            [
                'first_name' => 'Michelle',
                'last_name' => 'Walker',
                'date_of_birth' => '1993-04-08',
                'gender' => 'female',
                'email' => 'michelle.walker@email.com',
                'phone' => '+1-555-1031',
                'address' => '274 Highland Avenue',
                'city' => 'Nashville',
                'postal_code' => '37201',
                'emergency_contact_name' => 'Brandon Walker',
                'emergency_contact_phone' => '+1-555-1032',
                'medical_history' => 'Celiac disease',
                'allergies' => 'Gluten',
                'current_medications' => 'Multivitamin',
                'insurance_provider' => 'Humana',
                'insurance_policy_number' => 'HUM-33556677',
            ],
            [
                'first_name' => 'Kevin',
                'last_name' => 'Young',
                'date_of_birth' => '2008-12-15',
                'gender' => 'male',
                'email' => 'young.family@email.com',
                'phone' => '+1-555-1033',
                'address' => '618 Forest Lane',
                'city' => 'Dallas',
                'postal_code' => '75201',
                'emergency_contact_name' => 'Laura Young',
                'emergency_contact_phone' => '+1-555-1034',
                'medical_history' => 'Eczema',
                'allergies' => 'Dust mites',
                'current_medications' => 'Hydrocortisone cream as needed',
                'insurance_provider' => 'Blue Cross Blue Shield',
                'insurance_policy_number' => 'BCBS-66778899',
            ],
            [
                'first_name' => 'Rebecca',
                'last_name' => 'King',
                'date_of_birth' => '1980-10-22',
                'gender' => 'female',
                'email' => 'rebecca.king@email.com',
                'phone' => '+1-555-1035',
                'address' => '392 Sunset Boulevard',
                'city' => 'Las Vegas',
                'postal_code' => '89101',
                'emergency_contact_name' => 'Mark King',
                'emergency_contact_phone' => '+1-555-1036',
                'medical_history' => 'Fibromyalgia, chronic pain',
                'allergies' => 'Codeine, NSAIDs',
                'current_medications' => 'Duloxetine 60mg daily, Gabapentin 300mg three times daily',
                'insurance_provider' => 'Anthem',
                'insurance_policy_number' => 'ANT-88990011',
            ],
            [
                'first_name' => 'Timothy',
                'last_name' => 'Scott',
                'date_of_birth' => '1996-05-17',
                'gender' => 'male',
                'email' => 'timothy.scott@email.com',
                'phone' => '+1-555-1037',
                'address' => '507 Ocean Drive',
                'city' => 'Tampa',
                'postal_code' => '33601',
                'emergency_contact_name' => 'Emily Scott',
                'emergency_contact_phone' => '+1-555-1038',
                'medical_history' => 'Sports injury - healed shoulder dislocation',
                'allergies' => 'None known',
                'current_medications' => 'Ibuprofen as needed',
                'insurance_provider' => 'Cigna',
                'insurance_policy_number' => 'CIGNA-77665544',
            ],
        ];

        foreach ($patients as $patient) {
            Patient::create($patient);
        }
    }
}
